### ISSUE TITLE
Custom Skinning for Blitz Soundboard

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#11]
Pretty old and popular, and defacto main mod for creating and sharing/selling sound libraries in Foundry.

The UI is okay except the hardcoded blue could use to be changed with mid-to-darker gray, or dark cyan. 

![image](https://user-images.githubusercontent.com/4083812/125768361-f1ae16fc-87d6-44b4-9e1e-eb13a90d8f81.png)

**Comment by Rayuaz** [comment]
Added compatibility in the next update.
