### ISSUE TITLE
Compatibility with Polyglot and Monk's Enhanced Journal

### ISSUE THREAD

**Issue by tampotat** [Rayuaz/twilight-ui#12]
When using polyglot module the runes are replaced with random letters. 

![runes](https://user-images.githubusercontent.com/87482402/125793373-768be23d-161e-4e35-9572-0e0121c6b0f6.jpg)

And there are some minor visual glitches with Monk's Enhanced Journal.

**Comment by Rayuaz** [comment]
Added compatibility for both modules. Monk's sidebar folders don't look consistent with the folders in the app sidebar because he handles them a little differently, but I'll contact him and try to find a solution.
