### ISSUE TITLE
Minor issue with Moulinette Core

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#16]
Very popular mod backed by all big names in map making community.

Overall all is good, but the tabs could benefit from normalization of text and/or vertical centering in the tabs.

![image](https://user-images.githubusercontent.com/4083812/125798098-29e95eb4-4f30-4801-9ded-d04976ec652f.png)

Normally these fiends are on a single line, something in Twilight is causing it to break on two lines

![image](https://user-images.githubusercontent.com/4083812/125798299-86eb55b0-8b26-46ab-bd82-df149aa040d2.png)

**Comment by Rayuaz** [comment]
Fixed the controls bar, and found a better way to handle tabs.
