### ISSUE TITLE
[Bug] Thandul Toggables compatibility

### ISSUE THREAD

**Issue by MarceloCortezz** [Rayuaz/twilight-ui#19]
Hi Rayuaz!

I don't know what is causing this, but the Thandul Toggables icon and menu is all messed up, in the middle of the rest of the submenu icons:
![image](https://user-images.githubusercontent.com/79060716/125801952-7c62d6d8-5f4a-4bde-926f-be05bb9f7f02.png)

Below is the normal behaviour (no Twilight UI):
![image](https://user-images.githubusercontent.com/79060716/125802227-9ce24485-e1ab-43b1-939e-878eee14d322.png)

**Comment by Rayuaz** [comment]
I added basic compatibility with Thandul in the next update. For some reason, the icon disappears when you click on it, but other than that, it's working without any problems.
