### ISSUE TITLE
[ Suggestion ] Different chat cards for blind/public/self/private rolls

### ISSUE THREAD

**Issue by MarceloCortezz** [Rayuaz/twilight-ui#2]
Hey,

The Core FVTT chat cards have distinction between the different rolls (Blind/Private GM/Self/Public), with its background having some kind of texture (below image).
![image](https://user-images.githubusercontent.com/79060716/125718551-cc27437e-9541-4ca0-90af-0bc9b11657ed.png)

With Twilight UI, you have a little distinction between them, a blue border.
![image](https://user-images.githubusercontent.com/79060716/125718638-14c42583-fa19-4f8a-96e8-1d9af59578e3.png)

I'd like to know if it's possible to change the color of the card or something to ease identification of which type of roll is that card.

It's ok if this will not be implemented. Just making sure its possibility.

Thank you, anyways!

**Comment by Rayuaz** [comment]
Hey dude! I made whispers a little more distinctive in the last update. What do you think? 
![image](https://user-images.githubusercontent.com/67298960/125751516-edfebe29-08bc-496f-83f5-df1077dfed6d.png)

**Comment by MarceloCortezz** [comment]
YES! This is cool! I liked it! Thank you!

**Comment by Rayuaz** [comment]
Awesome, thanks for the feedback, dude!

**Comment by apoapostolov** [comment]
@Rayuaz without opening the issue, can you please give me the CSS line to override the color? I would like to switch it to dark red, to fit with DF Chat Enhancements style of red being private.
