### ISSUE TITLE
Compatibility with Combat Utility Belt

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#20]
![image](https://user-images.githubusercontent.com/4083812/125802343-6040546e-3d97-4431-a726-75078d7cc058.png)

![image](https://user-images.githubusercontent.com/4083812/125802390-67cd09d3-70c5-4b36-8a6f-0caa4f24cb9b.png)

**Comment by Rayuaz** [comment]
It's working fine on my end. Can you try narrowing down to which module is probably causing this?
![image](https://user-images.githubusercontent.com/67298960/125954889-80b12b85-33f4-4d12-86db-9a2701bd0b92.png)

**Comment by apoapostolov** [comment]
Try to turn off the CRT styling. 

![image](https://user-images.githubusercontent.com/4083812/125961875-ac8df130-a6f3-4ba0-96b5-3bd1c45b6d9d.png)

**Comment by Rayuaz** [comment]
That is also looking fine for me. The select menus have a white background (which I fixed), but other than that it's working fine. There must be another module causing touble in there somewhere. Can you inspect the window background element and give me a screenshot of the styles tab?

**Comment by apoapostolov** [comment]
Maybe I should have been clear here, the problem was the dropdown menu.

**Comment by Rayuaz** [comment]
Oh, my bad lol. But yeah, it has been fixed.
