### ISSUE TITLE
UI Issues with image journal folders

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#21]
* the image is not vertically centered against the text in the cell
* due to the lack of vertical centering above, the imagine causes a lot of empty space at the bottom, and less so on the top
* the imagine has rounded corners in the upper left and right corner, but hard corners in the lower left and hard corner. should be all rounded.

![image](https://user-images.githubusercontent.com/4083812/125802798-699f4bcf-1512-48e4-bf33-f73a7107c04d.png)

**Comment by Rayuaz** [comment]
What mod are you using to generate thumbnails?

**Comment by apoapostolov** [comment]
Sidebar Aesthetics
https://gitlab.com/Furyspark/foundryvtt-sidebar-aesthetics/

**Comment by Rayuaz** [comment]
Thanks for the feedback, dude! It has been fixed in v1.04.
