### ISSUE TITLE
Compatibility with Compendium Folders

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#22]
* Compendium Folders folder colors are not respected, they all appear black.
* Compendium Folders modal dialog on Edit Folder has a broken table for selecting what compendium to include in the folder

![image](https://user-images.githubusercontent.com/4083812/125832900-1b8f6cdf-6c43-44d0-8894-bc7ba0a611f1.png)

**Comment by Rayuaz** [comment]
There was an `!important` in the folder color, god knows why, but I removed it. About the menu, I have a new way to handle the `.form-group` class, which fixed this and a bunch other situations.
