### ISSUE TITLE
Compatibility with Party Overview

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#24]
The striped table looks very bad unless custom skinned

![image](https://user-images.githubusercontent.com/4083812/125834078-e00f5631-cf81-42e4-b2ac-0a05533a7789.png)

![image](https://user-images.githubusercontent.com/4083812/125834106-cbdcfde1-040a-45b7-9c65-d038cd5c8e2b.png)

![image](https://user-images.githubusercontent.com/4083812/125834128-e3a6b962-e732-4a1e-a4cf-8308df52a5ca.png)

![image](https://user-images.githubusercontent.com/4083812/125834148-607e246c-fd80-4860-b7a4-2af46ed67464.png)

**Comment by Rayuaz** [comment]
Fixed.
