### ISSUE TITLE
Compatibility with Monk's Token Bar

### ISSUE THREAD

**Issue by dirusulixes** [Rayuaz/twilight-ui#25]
Love the UI, but at the moment it makes the menus from [Monk's Token Bar module](https://github.com/ironmonk88/monks-tokenbar) almost impossible to use. 

![image](https://user-images.githubusercontent.com/5693623/125943973-22c54988-aeb8-4b0c-ab1d-060287c1fce1.png)
![image](https://user-images.githubusercontent.com/5693623/125946980-e3b37a91-7b00-45e5-8a73-19a605ebb993.png)

**Comment by Rayuaz** [comment]
Has been fixed for the next update (coming later today)

![image](https://user-images.githubusercontent.com/67298960/125967632-6ae4c1c0-44c9-46c4-ad02-5f86fbccb38f.png)
