### ISSUE TITLE
Scene right click configuration bug

### ISSUE THREAD

**Issue by tampotat** [Rayuaz/twilight-ui#29]
![runes](https://user-images.githubusercontent.com/87482402/126057770-b1997f3b-fd4e-4f0c-a9c0-9e75a248d043.jpg)

The configuration dropdown is hidden behind the scene thumbnails which makes it impossible to interact with. I tried it also with only the UI and dependencies modules enabled and the issue persisted, so this doesn't look like a conflict with another module.

**Comment by Rayuaz** [comment]
Thanks for the feedback, dude! It has been fixed in v1.04.
