### ISSUE TITLE
Tool control bar glitch after update to 8.9

### ISSUE THREAD

**Issue by tampotat** [Rayuaz/twilight-ui#33]
![image](https://user-images.githubusercontent.com/87482402/130587003-abaf9276-ec97-4d15-9e3f-4ddfe8906255.png)
This is how it looks like. It's like this for both players and GM. I have tested it with only Twilight UI module and dependencies, and the issue persists.

**Comment by Rayuaz** [comment]
Has been fixed in the latest update.
