### ISSUE TITLE
The left side of the controls are squarshed...

### ISSUE THREAD

**Issue by JaretheBear** [Rayuaz/twilight-ui#36]
I checked the modules and made sure it wasn't a compatibility issue, is there anything on my end to fix this? 
![image](https://user-images.githubusercontent.com/73076268/132061222-2fa0fec8-2b6d-4908-895e-6d5898b6101f.png)

**Comment by Rayuaz** [comment]
That's weird. I just checked and it's happening on my end aswell, which is weird because it wasn't happening last week and I don't recall updating my modules or Foundry since then. I'll investigate and release a hotfix as soon as possible.

**Comment by JaretheBear** [comment]
SO FAST! <3 Thank you!

**Comment by Rayuaz** [comment]
To be quite honest, I'm still not quite sure why this happend (I suspect it has to do with a chrome update), but I have released a hotfix.

**Comment by JaretheBear** [comment]
You are awesome! thank you much!
