### ISSUE TITLE
Element Height is duplicated for each row of scene buttons

### ISSUE THREAD

**Issue by FaeyUmbrea** [Rayuaz/twilight-ui#38]
For each row of scenes on screen, the element height is added to all rows of scenes.

Screnshot: https://i.imgur.com/1sy1Q4s.png

How to replicate:
1) Make a load of scenes
2) Add to navigation
3) Resize window or keep adding scenes to add more rows.

**Comment by Rayuaz** [comment]
Has been fixed in the latest update. Thanks for the report!
