### ISSUE TITLE
Very thin dark gray border around modal dialogs to make them visible in dark/black backgrounds

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#4]
Modal dialogs use their shape when they are placed against very dark backgrounds or black solid color. It would be nice if very dark but gray color had 1px border around them, so they can be distinguished. 

![image](https://user-images.githubusercontent.com/4083812/125751599-a6c5dd05-5ca0-4f1c-9556-e7d1745761e4.png)

**Comment by Rayuaz** [comment]
I made the header a lot lighter, so it doesn't meld with the box shadow on dark backgrounds. It'll be in the next update.
