### ISSUE TITLE
feature request: compatibility with Changelogs module

### ISSUE THREAD

**Issue by dirusulixes** [Rayuaz/twilight-ui#41]
At the moment [Changelog](https://github.com/theripper93/libChangelogs) is not themed and the text is barely legible unfortunately.
![image](https://user-images.githubusercontent.com/5693623/133637086-fa0cba63-8682-4d84-9398-0ee789b1fd8b.png)

**Comment by Rayuaz** [comment]
Why would someone declare font color black? It's black by default 👺

Anyway, it's fixed now. I release an update tonight.
