### ISSUE TITLE
Generic way to avoid spillouts of button labels on two lines

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#6]
Prevent spilling out of labels outside of containers. Maybe some logic that could remove the button label and leave just icon in such cases. 

![image](https://user-images.githubusercontent.com/4083812/125752278-66dcf183-2166-4170-a2a8-b8168a1709bb.png)

![image](https://user-images.githubusercontent.com/4083812/125751978-9aada2e9-f85d-4623-8226-fb61602bfcec.png)

**Comment by Rayuaz** [comment]
I added a new, smarter button layout which will be available in the next update.
