### ISSUE TITLE
Compatibility support for GM Screen mod

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#7]
Just the tabs need love

![image](https://user-images.githubusercontent.com/4083812/125752569-9b7dc01a-1dba-49bc-be52-e4dc74995970.png)

**Comment by Rayuaz** [comment]
Fixed.

**Comment by apoapostolov** [comment]
@Rayuaz Maybe tabs other than selected should be darker gray than this, see Names. 

![image](https://user-images.githubusercontent.com/4083812/125987466-eb06ebf1-54e8-4ea2-a732-1f4ccc3e4896.png)
