### ISSUE TITLE
Compatibility with Blitz' SocketSettings

### ISSUE THREAD

**Issue by apoapostolov** [Rayuaz/twilight-ui#8]
Great mod that lets GM propagade their settings to all online players. Buttons added to each setting that can be propagated are broken, bad readability and no width

![image](https://user-images.githubusercontent.com/4083812/125753138-5fcf76e1-8c19-4ce7-9ec5-23ef67c7f495.png)

**Comment by Rayuaz** [comment]
Fixed.
